# Generated by Django 4.2.7 on 2023-11-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default=1, upload_to='media/players', verbose_name='Player image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
    ]
